### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by six5536**
Hi, cool plugin.

I've made some changes to stop Gatsby spitting an Error (fs.promises) if using in Node 10.x.

I've also added typescript-resolvers plugin for those using GraphQL resolvers.

I've also added some different generation flags. I think the generation flags / config should be configurable in the plugin, but haven't got time to do that at the mo.

### CODE REVIEW

**Comment by six5536** [comment]
Hi,

I've made some more changes:

fix: improved performance significantly by reducing unnecessary calls
fix: ignore generated types when watching for changes
fix: reload schemaAst for codegen on schema changes

Would be great to get these merged!

**Comment by cometkim** [comment]
Hey @relefant, thank you for cool PR and sorry for my late response. 

> I've made some changes to stop Gatsby spitting an Error (fs.promises) if using in Node 10.x.

This was intended and the reason why there is node >= 10 in package.json

> I think the generation flags / config should be configurable in the plugin, but haven't got time to do that at the mo.

totally agree with you. I've been busy recently too, so I didn't have time to maintain this project.

I have a single question and no problems to merge this. What the resolvers plugin is for? Schema Customization?

**Comment by six5536** [comment]
The resolvers plugin creates types when you extend the schema using GraphQL resolvers.
See Gatsby createResolvers API:
https://www.gatsbyjs.org/docs/node-apis/#createResolvers

PS Great that you are merging these changes now.

**Comment by cometkim** [comment]
Hey @relefant, I will release 1.0 soon after merging some additional changes.

Thank you for your contribution!

**Pull request merged**
